-- Create the leads table
create table leads (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  email text not null,
  phone text,
  destination text,
  dates text,
  travelers text,
  notes text,
  status text default 'new',
  admin_notes text
);

-- Enable Row Level Security (RLS)
alter table leads enable row level security;

-- Create policies
-- 1. Allow public to insert (for the contact form)
create policy "Public can insert leads"
on leads for insert
to anon
with check (true);

-- 2. Allow anon (admin with correct setup) to select/update
-- NOTE: In a real production app, you'd want authenticated users only.
-- For this simple dashboard, we will allow the "anon" key to read/update for now 
-- so the dashboard works without setting up complex Auth providers yet.
create policy "Enable access for all users"
on leads for select
to anon
using (true);

create policy "Enable update for all users"
on leads for update
to anon
using (true);

-- Reviews Table for Customer Testimonials
create table public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text not null, -- e.g. "Luna de Miel", "Familia"
  content text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  is_approved boolean default true -- Auto-approve for now, can change to false later
);

-- RLS Policies for Reviews
alter table public.reviews enable row level security;

create policy "Enable read access for all users" on public.reviews
  for select using (true);

create policy "Enable insert access for all users" on public.reviews
  for insert with check (true);

-- Update Reviews Table with Image URL
alter table public.reviews add column image_url text;

-- Create Storage Bucket for Reviews
insert into storage.buckets (id, name, public) 
values ('reviews', 'reviews', true);

-- Storage Policies
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'reviews' );

create policy "Public Upload"
on storage.objects for insert
with check ( bucket_id = 'reviews' );

-- Migration: Add new fields for advanced lead management
ALTER TABLE leads
ADD COLUMN IF NOT EXISTS probability integer,
ADD COLUMN IF NOT EXISTS check_in date,
ADD COLUMN IF NOT EXISTS check_out date,
ADD COLUMN IF NOT EXISTS provider_classification text,
ADD COLUMN IF NOT EXISTS price numeric,
ADD COLUMN IF NOT EXISTS commission numeric,
ADD COLUMN IF NOT EXISTS payment_status text,
ADD COLUMN IF NOT EXISTS booking_reference text,
ADD COLUMN IF NOT EXISTS quote_sent_date date,
ADD COLUMN IF NOT EXISTS estimated_sale_amount numeric;

-- Create tasks table for client follow-ups
CREATE TABLE IF NOT EXISTS public.tasks (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  lead_id uuid REFERENCES public.leads(id) ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  description text,
  due_date date NOT NULL,
  status text DEFAULT 'not_started' NOT NULL CHECK (status IN ('not_started', 'in_process', 'completed'))
);

-- Enable RLS
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Policies for tasks
CREATE POLICY "Enable read access for all users" ON public.tasks
  FOR SELECT USING (true);

CREATE POLICY "Enable insert access for all users" ON public.tasks
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update access for all users" ON public.tasks
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete access for all users" ON public.tasks
  FOR DELETE USING (true);

-- Create resources table for Customer Resource Center
CREATE TABLE IF NOT EXISTS public.resources (
  id text PRIMARY KEY,
  title text NOT NULL,
  category text NOT NULL CHECK (category IN ('wdw', 'dl', 'dcl')),
  pdf_url text,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for resources
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;

-- Policies for resources
CREATE POLICY "Enable read access for all users" ON public.resources
  FOR SELECT USING (true);

CREATE POLICY "Enable insert access for all users" ON public.resources
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update access for all users" ON public.resources
  FOR UPDATE USING (true);

-- Seed initial resources config
INSERT INTO public.resources (id, title, category) VALUES
  ('wdw_mde', 'GUÍA MY DISNEY EXPERIENCE', 'wdw'),
  ('wdw_ll', 'GUÍA RESERVAS Lightning Lane', 'wdw'),
  ('wdw_overview', 'GUÍA Overview Disney World', 'wdw'),
  ('wdw_dining', 'Guía Dining Plan', 'wdw'),
  ('wdw_dining_char', 'Restaurantes - Experiencias con personajes', 'wdw'),
  ('wdw_dining_req', 'Restaurantes - Requieren reservacion', 'wdw'),
  ('dl_app', 'GUÍA Disneyland APP', 'dl'),
  ('dl_ll', 'GUÍA RESERVAS Lightning Lane', 'dl'),
  ('dl_overview', 'GUÍA Overview Disneyland', 'dl'),
  ('dl_dining_char', 'Restaurantes - Experiencias con personajes', 'dl'),
  ('dl_dining_req', 'Restaurantes - Requieren reservacion', 'dl'),
  ('dcl_overview', 'Overview', 'dcl'),
  ('dcl_deck', 'Deck Plan', 'dcl')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category;

-- Migration: Add new fields for resource access in leads
ALTER TABLE public.leads
ADD COLUMN IF NOT EXISTS resource_access_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS resource_pin text DEFAULT null,
ADD COLUMN IF NOT EXISTS resource_wdw boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS resource_dl boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS resource_dcl boolean DEFAULT false;

-- Create Storage Bucket for Resources
INSERT INTO storage.buckets (id, name, public) 
VALUES ('resources', 'resources', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies for Resources
CREATE POLICY "Public Access Resources"
ON storage.objects FOR select
USING ( bucket_id = 'resources' );

CREATE POLICY "Public Upload Resources"
ON storage.objects FOR insert
WITH CHECK ( bucket_id = 'resources' );

CREATE POLICY "Public Update Resources"
ON storage.objects FOR update
WITH CHECK ( bucket_id = 'resources' );

CREATE POLICY "Public Delete Resources"
ON storage.objects FOR delete
USING ( bucket_id = 'resources' );


-- ----------------------------------------------------
-- CMS TABLES & POLICIES (REVIEWS, GALLERY, ABOUT ME, DESTINATIONS, BLOG)
-- ----------------------------------------------------

-- 1. Ensure Reviews policies support UPDATE and DELETE
CREATE POLICY "Enable update access for reviews" ON public.reviews
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete access for reviews" ON public.reviews
  FOR DELETE USING (true);


-- 2. Homepage Gallery Table & Policies
CREATE TABLE IF NOT EXISTS public.homepage_gallery (
  id text PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  image_url text NOT NULL,
  alt text DEFAULT '',
  sort_order integer DEFAULT 0
);

ALTER TABLE public.homepage_gallery ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for gallery" ON public.homepage_gallery FOR SELECT USING (true);
CREATE POLICY "Enable insert access for gallery" ON public.homepage_gallery FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for gallery" ON public.homepage_gallery FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for gallery" ON public.homepage_gallery FOR DELETE USING (true);

-- Storage bucket for gallery
INSERT INTO storage.buckets (id, name, public) 
VALUES ('gallery', 'gallery', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Access Gallery" ON storage.objects FOR SELECT USING ( bucket_id = 'gallery' );
CREATE POLICY "Public Upload Gallery" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'gallery' );
CREATE POLICY "Public Update Gallery" ON storage.objects FOR UPDATE WITH CHECK ( bucket_id = 'gallery' );
CREATE POLICY "Public Delete Gallery" ON storage.objects FOR DELETE USING ( bucket_id = 'gallery' );


-- 3. Site Settings Table (About Me & Global Config)
CREATE TABLE IF NOT EXISTS public.site_settings (
  key text PRIMARY KEY,
  value text NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for site_settings" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Enable insert access for site_settings" ON public.site_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for site_settings" ON public.site_settings FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for site_settings" ON public.site_settings FOR DELETE USING (true);


-- 4. Destinations Table
CREATE TABLE IF NOT EXISTS public.destinations (
  slug text PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  title text NOT NULL,
  subtitle text,
  hero_image text,
  overview text,
  highlights text,
  must_dos text,
  tips text
);

ALTER TABLE public.destinations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for destinations" ON public.destinations FOR SELECT USING (true);
CREATE POLICY "Enable insert access for destinations" ON public.destinations FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for destinations" ON public.destinations FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for destinations" ON public.destinations FOR DELETE USING (true);


-- 5. Blog Posts Table
CREATE TABLE IF NOT EXISTS public.blog_posts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  slug text UNIQUE NOT NULL,
  title text NOT NULL,
  excerpt text,
  content text,
  date text,
  read_time text,
  image text,
  category text
);

ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for blog_posts" ON public.blog_posts FOR SELECT USING (true);
CREATE POLICY "Enable insert access for blog_posts" ON public.blog_posts FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for blog_posts" ON public.blog_posts FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for blog_posts" ON public.blog_posts FOR DELETE USING (true);


